CREATE TABLE SZEMELY (
    ID BIGINT NOT NULL,
    VEZETEKNEV VARCHAR(50) NOT NULL,
    KERESZTNEV VARCHAR(50) NOT NULL,
    SZEMELYIAZON VARCHAR(30) NOT NULL,
    LAKCIMAZON VARCHAR(20) NOT NULL,
    CONSTRAINT ID PRIMARY KEY (ID));
